<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Apellido' => '',
    'Accion' => 'Acción',
    'Are you sure you want to delete this item?' => 'Está seguro que desea eliminar este item?',
    'AutoTextos' => '',
    'Borrar' => '',
    'Calle' => '',
    'Cantidad' => '',
    'Cantidad Produccion' => 'Cantidad de Producción',
    'Categoria' => '',
    'Categorias' => '',
    'Ciudad ' => '',
    'Cliente ID' => '',
    'Clientes' => '',
    'Codigo Postal' => 'Código Postal',
    'Comanda Detalles' => 'Detalles de Comanda',
    'Comanda ID' => '',
    'Comandas' => '',
    'Crear Pedido Manual' => '',
    'Create Categoria' => 'Nueva Categoría',
    'Create Comanda' => 'Nueva Comanda',
    'Create Comanda Detalle' => '',
    'Create Domicilio' => 'Nuevo Domicilio',
    'Create Pedido Detalle' => '',
    'Create Pedido Manual' => '',
    'Create Producto' => 'Nuevo Producto',
    'Create Rol' => 'Nuevo Rol',
    'Create User' => 'Nuevo Usuario',
    'Delete' => 'Eliminar',
    'Detalle' => '',
    'Detalle de Comanda ' => '',
    'Direccion 1' => 'Dirección 1',
    'Direccion 2' => 'Dirección 2',
    'Domicilios' => '',
    'Editar' => '',
    'Email' => '',
    'Empresa' => '',
    'Estado' => '',
    'Fecha Hora' => '',
    'Fecha Produccion' => 'Fecha de Producción',
    'ID' => '',
    'Listado de Clientes' => '',
    'Listado de Comandas' => '',
    'Listado de Pedidos' => '',
    'Listado de Productos' => '',
    'Nombre' => '',
    'Nota' => '',
    'Nro' => '',
    'Nuevo AutoTexto' => '',
    'Pais' => 'País',
    'Password Web' => 'Contraseña Web',
    'Pedido Detalles' => '',
    'Pedido ID' => '',
    'Pedidos' => '',
    'Precio Linea' => 'SubTotal',
    'Precio Total' => 'Total',
    'Precio Unitario' => '',
    'Producto ID' => '',
    'Productos' => '',
    'Provincia' => '',
    'Razon Social' => 'Razón Social',
    'Reset' => 'Restablecer',
    'Rol ' => '',
    'Rol ID' => '',
    'Rols' => '',
    'Search' => 'Buscar',
    'Sincronizar Cliente ' => '',
    'Sincronizar Pedidos' => '',
    'Sincronizar Web' => '',
    'Sincronizar con la Web' => '',
    'Update' => 'Modificar',
    'Update ' => 'Modificar ',
    'Update {modelClass}: ' => 'Modificar {modelClass}:',
    'Users' => 'Usuarios',
    'Usuario Web' => '',
    'Usuarios' => '',
    'View' => 'Ver',
    'Web Customer ID' => '',
    'Web ID' => '',
    'Categoria ID' => '@@@@',
    'Create Pedido' => '@@@@',
    'Domicilio ID' => '@@@@',
    'Productocol' => '@@@@',
    'Create' => 'Crear',
    'Create Cliente' => 'Nuevo Cliente',
];
